context:
  name: rainfrog
  version: "0.3.17"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/achristmascarl/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: bc5aa6a366433531885fc6b730c8f6b03e405792bff54ca0e9168891b6d9f589

build:
  number: 1
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - if: linux and ppc64le
      then: cargo install --no-track --locked --root ${{ PREFIX }} --path . --no-default-features --features arboard
      else: cargo install --no-track --locked --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - rainfrog --version
      - rainfrog --help

about:
  homepage: https://crates.io/crates/rainfrog
  summary: '🐸 a database management tui for postgres'
  description: |
    The goal for rainfrog is to provide a lightweight, terminal-based alternative to pgadmin/dbeaver.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/achristmascarl/rainfrog/

extra:
  recipe-maintainers:
    - achristmascarl
    - eunos-1128
