context:
  name: rainfrog
  version: "0.3.14"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/achristmascarl/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 55d6a77dbfea16d34d1cb95694895de698ffc947a6320e621b509b512d15a7ff

build:
  number: 0
  script:
    - if: osx and arm64
      then: |
        export LIBRARY_PATH="${BUILD_PREFIX}/lib:${LIBRARY_PATH:-}"
        export LD_LIBRARY_PATH="${BUILD_PREFIX}/lib:${LD_LIBRARY_PATH:-}"
        export DYLD_LIBRARY_PATH="${BUILD_PREFIX}/lib:${DYLD_LIBRARY_PATH:-}"
        export LIBICONV_LIB_DIR="${BUILD_PREFIX}/lib"
        export LIBICONV_INCLUDE_DIR="${BUILD_PREFIX}/include"
        export LIBGIT2_SYS_USE_PKG_CONFIG=1
        export RUSTFLAGS="-L${BUILD_PREFIX}/lib -l c++ -l iconv ${RUSTFLAGS:-}"
        export LDFLAGS="-L${BUILD_PREFIX}/lib -liconv"
        
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - if: linux and ppc64le
      then: cargo install --no-track --locked --root ${{ PREFIX }} --path . --no-default-features --features arboard
      else: cargo install --no-track --locked --root ${{ PREFIX }} --path .

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - if: build_platform != target_platform
      then: libiconv

tests:
  - script:
      - rainfrog --version

about:
  homepage: https://crates.io/crates/rainfrog
  summary: '🐸 a database management tui for postgres'
  description: |
    The goal for rainfrog is to provide a lightweight, terminal-based alternative to pgadmin/dbeaver.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/achristmascarl/rainfrog/

extra:
  recipe-maintainers:
    - achristmascarl
    - eunos-1128
