context:
  name: rainfrog
  version: "0.3.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/achristmascarl/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1d9322296b8fb0c789ad3a3b13284f39e15a55efb479b3d2e2d5954ec3c0ea73

build:
  script:
    - if: osx
    - then:
      - |
        if [[ "${target_platform}" == "osx-arm64" ]]; then
          export LIBICONV_LIB_DIR="${PREFIX}/lib"
          export LIBICONV_INCLUDE_DIR="${PREFIX}/include"
        fi
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --no-track --locked --root ${{ PREFIX }} --path .

  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
  host:
    - if: osx
      then: libiconv

tests:
  - script:
      - rainfrog --version

about:
  homepage: https://crates.io/crates/rainfrog
  summary: '🐸 a database management tui for postgres'
  description: |
    The goal for rainfrog is to provide a lightweight, terminal-based alternative to pgadmin/dbeaver.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  repository: https://github.com/achristmascarl/rainfrog/

extra:
  recipe-maintainers:
    - achristmascarl
    - eunos-1128
